### ISSUE TITLE
would be neat ot have functionality that would let you perform ordered aggregations

### ISSUE THREAD

**Issue by limbolabs** [ReadyForZero/babbage#11]
eg: 
- what is the balance of an account on the first of every month, 
- number of events until the first of every month

**Comment by bwo** [comment]
assigned to right person?

**Comment by limbolabs** [comment]
accident, reassigned

**Comment by limbolabs** [comment]
just to motivate this, i'm trying to collect stuff for reports like:

{:months [{:name "August" 
                :start 200 :new 30 :cancelled 15 :net 15 :end 215 :net-dollars "$4214.23"
                :net-dollars "$12231.12"
                }]})

it would be nice to have a language to express this aggregation on streams

**Comment by bwo** [comment]
where the input just has timestamps, I take it?

**Comment by ithayer** [comment]
times or timestamps and other fields, eg:

{:ts 123 :billed 123.23}

**Comment by bwo** [comment]
Actually the "first" in that commit will only do the desired thing if the input is sorted by timestamp; otherwise, it would just find the first account in the relevant timespan in the input seq, though there might be another, with an earlier timestamp, later in the input---getting around _that_ is more complicated.

Also I suppose the function should be group-by rather than split-with.
