### ISSUE TITLE
xget should work on set compositions

### ISSUE THREAD

**Issue by ithayer** [ReadyForZero/babbage#6]
instead of having to declare the entire set names, it would be nice if it used the composition functions, eg: the "intersections" forms

**Comment by bwo** [comment]
Not sure where this would go in xget itself. There's are already intersection-name and union-name functions (complement-name would be worth adding) for generating the names of derived sets from the names of input sets.

Xget could also just return the results across _all_ sets, but as long as you want to be able to specify only _some_ sets, it seems like an issue about getting set names rather than directly about xget.

**Comment by bwo** [comment]
closed by 2e2183d2
